[package]
name = "ragtime"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[[bin]]
name = "test-encode"

[[bin]]
name = "test-chunk"

[[bin]]
name = "test-gen"

[features]
vulkan = ["llama-cpp-2/vulkan"]
native = ["llama-cpp-2/native"]

[dependencies]
#ort = "2.0.0-rc.2"
ort = { git = "https://github.com/pykeio/ort.git" }
anyhow = "1"
tracing-subscriber = "0.3"
tokenizers = "0.19"
ndarray = "0.15"
usearch = { version = "2.12.0", features = ["fp16lib"] }
half = { version = "2.4.1", features = ["num-traits"] }
memmap2 = "0.9.4"
serde = "1"
serde_derive = "1"
serde_json = "1"
fxhash = "0.2"
chrono = "0.4.38"
indexmap = "2.2.6"
llama-cpp-2 = { path = "../llama-cpp-rs/llama-cpp-2" }
encoding_rs = "0.8.34"
compact_str = "0.7.1"
