[package]
name = "ragtime"
version = "0.1.0"
edition = "2021"

[profile.release]
codegen-units = 1
opt-level = 3
lto = true
debug = false

[[bin]]
name = "test-encode"

[dependencies]
#ort = "2.0.0-rc.2"
ort = { git = "https://github.com/pykeio/ort.git" }
anyhow = "1"
tracing-subscriber = "0.3"
tokenizers = "0.19"
ndarray = "0.15"
usearch = { version = "2.12.0", features = ["fp16lib"] }
half = { version = "2.4.1", features = ["num-traits"] }
